[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/tsuru/go-tsuruclient"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
